### ISSUE TITLE
Compilation fails using v0.32.0 + C++11 + clang & gcc + CMake & Autotools

### ISSUE THREAD

**Issue by sxleixer** [eclipse/sumo#4110]
During compilation of v0.32.0 I experienced compilation errors for both clang and gcc.

The first problem was the following:
```
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/map:60:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/bits/stl_tree.h:452:7: error: static_assert failed due to requirement '__is_invocable<Named::ComparatorIdLess &, MSLane *const &, MSLane *const &>{}' "comparison object must be invocable with two arguments of key type"
      static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/bits/stl_set.h:133:17: note: in instantiation of template class 'std::_Rb_tree<MSLane *, MSLane *, std::_Identity<MSLane *>, Named::ComparatorIdLess, std::allocator<MSLane *> >' requested here
      _Rep_type _M_t;  // Red-black tree representing set.
                ^
<PATH_TO_SUMO>/src/microsim/MSEdgeControl.h:223:48: note: in instantiation of template class 'std::set<MSLane *, Named::ComparatorIdLess, std::allocator<MSLane *> >' requested here
    std::set<MSLane*, Named::ComparatorIdLess> myChangedStateLanes;
                                               ^
In file included from <PATH_TO_SUMO>/src/traci-server/TraCIServerAPI_Edge.cpp:39:
In file included from <PATH_TO_SUMO>/src/microsim/MSNet.h:49:
In file included from <PATH_TO_SUMO>/src/utils/common/NamedRTree.h:34:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/set:61:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.1.0/../../../../include/c++/8.1.0/bits/stl_set.h:147:35: error: no type named 'const_iterator' in 'std::_Rb_tree<MSLane *, MSLane *, std::_Identity<MSLane *>, Named::ComparatorIdLess, std::allocator<MSLane *> >'
      typedef typename _Rep_type::const_iterator         iterator;
              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
<PATH_TO_SUMO>/src/microsim/MSEdgeControl.h:223:48: note: in instantiation of template class 'std::set<MSLane *, Named::ComparatorIdLess, std::allocator<MSLane *> >' requested here
    std::set<MSLane*, Named::ComparatorIdLess> myChangedStateLanes;
```

This boils down to an compilation error in `src/utils/common/Named.h`. I fixed it using `<type_traits>` and `static_assert`. The `SFINAE` solution didn't work.

```
32a33
> #include <type_traits>
81,82c82,85
<         bool operator()(Named* const a, Named* const b) const {
<             return a->getID() < b->getID();
---
>         template<typename T>
>         bool operator()(T* const a, T* const b) const {
>             static_assert(std::is_same<T, Named>::value, "Must be object of type Named");
>             return false;
```

The second error was in `src/utils/gui/GUIVideoEncoder.h` the following patch fixes it:

```
165c165
<                 CODEC_CAP_DELAY)) {
---
>                 AV_CODEC_CAP_DELAY)) {
```

Which C++ version are you targeting? As I'm experiencing lots and lots of `warning` and `deprecation` messages I feel you're targeting below C++11. I usually use C++11 and above.

**Comment by namdre** [comment]
We are targeting C+11 since 2017 but most of our code base still uses C++98.
Our nightly builds with gcc, clang and msvc have not yet produced the issues you mention.
Can you please check if the latest development version from the repository also fails to build on your end?

**Comment by sxleixer** [comment]
Yes, checked out `origin/master` right now. At least I get the same error for the `Named.h` file. I think this is because the compiler does not resolve `_Key` as a subtype of `Named`.

My solution fixes this issue.

**Comment by sxleixer** [comment]
I fixed all the issues I found in the code. Including all warnings I could clean up. I have to admit - I don't have a clue how to pass this piece of code to you using something like pull requests.

I did a small code review and here some points I would consider to change:

- Add `-Wall -Werror -pedantic` to `CMAKE_C_FLAGS_DEBUG` and `CMAKE_CXX_FLAGS_DEBUG`. Warnings, in my opinion, are there for a reason, so cleaning them all out contributes to code quality.
- In the code `auto` is not used. There are situations in which `auto` is good practice and other situations where `auto` may be harmful. The rule of thumb: Whenever you use `auto` out of laziness - it is harmful. Whenever you use `auto` to keep the code `DRY` it is good practice. For example in explicit casts `auto` must be used. Whenever you're using `iterators` in loops use `auto`.
- Sometimes the coder seemed to be very paranoid. For example when a `const_iterator` is dereferenced and casted to its `const` pointer during the call of a `const` suffix qualified function. However, `const` suffix qualified functions cannot alter the state of the called object nor of class members. This means whenever I call another function in the `const` suffix qualified context that function has to be `const` suffix qualified. Though this is not a programming error - it renders the code unreadable.
- There are numerous places where `static_cast` is used instead of `dynamic_cast`. Use `static_cast` to cast to the more general class and `dynamic_cast` to cast to the more special class.
- Consider using smart pointers. Not because they are handy, because they transport ownership information. E. g. a `std::shared_ptr` has distributed ownership, a `std::weak_ptr` makes clear that the bearer of the pointer neither controls nor owns the object, a `std::unique_ptr` traverses ownership to the bearer of the pointer.
- Consider some sort of linting. This will simplify lots of constructions and improve code quality.
- There are numerous places where an `implicit fallthrough` takes place in the  `switch` cases. With a background in C# programming I'm a fan of using break at the end of each `case` or explicitly use a `goto` to the next switch case. This explicitly reflects the will of the programmer to jump to the next switch case - without putting out some sort of error (This is the only case where I use `goto`). Another way is to use `[[implicit_fallthrough]];` at the end. However, this is `C++17` and any other possibility to silence this warning is compiler specific.
- Throw exceptions `by value` - catch exceptions `by reference`! There are a handful of catch cases where the exceptions are caught `by value` - therefore the copy constructor is used although not needed.

I'm aware that nearly all advice I gave is only correct to some extent. Which means that there might be some pathologies where the advice doesn't hold.

**Comment by sxleixer** [comment]
I published my changes to the repository on:
https://gitlab.ralfschleicher.de/visible/SUMO

**Comment by namdre** [comment]
the issue with GUIVideoEncoder was already fixed (#3774)

**Comment by namdre** [comment]
Can you please check whether you can build master now with your toolchain?

**Comment by mightyCelu** [comment]
I am also affected by the issue and with the current master (e77c7f77e41638050fffd94f0e330ee708f6973a) the problem still occurs:
```
In file included from /usr/include/c++/8.1.0/map:60,
                 from //sumo/src/utils/geom/GeoConvHelper.h:32,
                 from //sumo/src/libsumo/Simulation.cpp:31:
/usr/include/c++/8.1.0/bits/stl_tree.h: In instantiation of ‘class std::_Rb_tree<MSLane*, MSLane*, std::_Identity<MSLane*>, Named::NamedLikeComparatorIdLess<Named>, std::allocator<MSLane*> >’:
/usr/include/c++/8.1.0/bits/stl_set.h:133:17:   required from ‘class std::set<MSLane*, Named::NamedLikeComparatorIdLess<Named> >’
//sumo/src/microsim/MSEdgeControl.h:221:48:   required from here
/usr/include/c++/8.1.0/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sxleixer** [comment]
Same problem as mightyCelu discovered.

**Comment by jimonreal** [comment]
I have the same issue here.
Same C++ version.
Running,

git clone --recursive https://github.com/eclipse/sumo.git
git fetch origin refs/replace/*:refs/replace/*
make -f Makefile.cvs
./configure
make

**Comment by sxleixer** [comment]
Oh okay I see - you're right my solution is too special. What about:

```
static_assert(std::is_convertible<T, Named>::value, "T must be of type Named or a derivative of Named")
```

**Comment by jimonreal** [comment]
It seems to be a problem with the version of C++. I have seen the same error all over different projects.

**Comment by jimonreal** [comment]
I have downgraded my GCC to version 7.3, and I was able to build and run sumo. So there must be something in the code generating an error with the newest version of GCC. What is the version of GCC that runs in the nightly build @namdre ?

**Comment by sxleixer** [comment]
I suggest using the following substitution in `utils/common/Named.h`. I tested this snippet on various compiler versions for `Clang` and `GCC`.

```
struct ComparatorIdLess {
    template <typename T>
    bool operator()(const T* const a, const T* const b) const {
        return a->getID() < b->getID();
    }
};
```

Advantages:
- It handles all classes which implement a `getID()` function of comparable type
- It's a one fits all solution therefore the `NamedLikeComparatorIdLess` is no more needed
- When a class does not meet the `getID` function criteria a compile time error is thrown.

Disadvantages:
- It is not a tight fit solution, since every class implementing a `getID` function of comparable type will meet the criteria.

If you want to make this a tight fit solution add following part to the function body:
```
static_assert(
    std::is_convertible<T, Named>::value || std::is_convertible<T, SUMOVehicle>::value,
    "Not of valid class `Named` or `SUMOVehicle`"
);
```

This will throw a compile time error, when criteria is not met and will not affect runtime performance.

**Comment by namdre** [comment]
@jimonreal You are correct. This error only shows up with never versions of gcc and clang. The code which throws the error is old and has been running for years. We have been building it with all versions of msvc between msvc10 and mvsc17. Our gcc toolchain is maybe a bit dusty. We are currently building with gcc versions  4.8  and 5.4 on different computers. clang is running at 3.4, 3.7 and 3.8

@sxleixer In master this code is already used. In fact, that function did already exist under a slightly different name but was not used for subclasses of Named to simplify the code in other parts. Yesterday I tried to use 
```
    template <class NamedLike>
    struct NamedLikeComparatorIdLess {
        bool operator()(const NamedLike* const a, const NamedLike* const b) const {
            return a->getID() < b->getID();
        }
    };   
    typedef NamedLikeComparatorIdLess<Named> ComparatorIdLess;

```
which again works fine with older gcc versions but gcc 8.1 is still unhappy. According to my understanding, the code is valid C++ and I have some hope that the latest gcc gets around to seeing it that way as well. Nevertheless I'll try my best to get a workaround uploaded as soon as I have my own gcc 8.1 toolchain up so I don't have to keep guessing.

@sxleixer re: your code style suggestions. Thanks for the comments. You make a lot of good points. Some of them already reflect our current coding style. It's just that we did not want to pour to much resources in digging up older code that has been working nicely for some time. (i.e. usage of auto). Current policy is to freshen up old code whenever we change things. Regarding the warnings, we were running gcc with pedantic and always try to have a 0-warning build. clang seems to warn a bit and was missing the pedantic flag until yesterday.

**Comment by sxleixer** [comment]
@namdre I googled the error and found following [fix](https://github.com/cseed/arachne-pnr/pull/111/commits/878ea31c1148d84fd509bcad4fad567d5f4489f5).

This unions my approach with your approach and is still explicit. It also compiles for lower versions of Clang and GCC.

```c++
template <class NamedLike>
struct NamedLikeComparatorIdLess {
    template<class T>
    bool operator()(const T* const a, const T* const b) const {
        return static_cast<const NamedLike*>(a)->getID() < static_cast<const NamedLike*>(b)->getID();
    }
};
typedef NamedLikeComparatorIdLess<Named> ComparatorIdLess;
```

**Comment by jimonreal** [comment]
It worked perfect with GCC 8.1.0 Thank you @namdre and @sxleixer for the help

**Comment by mightyCelu** [comment]
The commit appears to work for me (build is still running with clang, but it already passed the location of the error).

However, I still don't understand the issue completely:
- The new compiler releases did not actually change the code semantics, rather they added checks to ensure the given types fulfil the constraints. Given that the code worked so far, it looks like the compiler check is too restrictive. 
- I tried to create a minimal example to reproduce the error. It uses the comparater as is, and contains a Named class which only provides getId(), as well as a derived class. This compiles without issues.
- The error occurs because `__is_invocable<Named::NamedLikeComparatorIdLess<Named> &, MSLane *const &, MSLane *const &>{}` is false, however, from looking at its parameters it looks like it should.
Can you clarify this maybe? I feel that understanding the problem will be helpful even if there is a usable workaround now.

**Comment by sxleixer** [comment]
@mightyCelu I also made a minimal example but could not reproduce this error. As I read somewhere the problem might be that `MSLane` may be an incomplete type. So the expression cannot be evaluated correctly. I will heading down this road this evening.

**Comment by jimonreal** [comment]
Regarding to what @mightyCelu just said, I would like to understand also what is the problem with the code

**Comment by mightyCelu** [comment]
@sxleixer You're right, the issue is MSLane being of incomplete type. I was able to modify my minimal example such that it breaks iff the key is a pointer of incomplete type.

The present fix uses two template parameters, which is not necessary. I wrote to alternative fixes to this issue. Unfortunately both require changes to the type, which changes its usage a bit.

* The first version (https://github.com/mightyCelu/sumo/commit/91a24799231538e79079e6be786d40dbbdce24bf) uses a default template parameter and thus avoids having both `ComparatorIdLess` and `NamedLikeComparatorIdLess`. Therefore, usages of the latter need to be changed to the former and usages without templates need to pass an empty template parameter list.
* The second version (https://github.com/mightyCelu/sumo/commit/a5af0d5ae849ef32c883663465b09a5592e6d65b) moves the template parameter from the comparator type to the operator method. I assume this is what also fixes the issue in the fix @sxleixer proposed. Getting rid of the template parameter on the type changes the usage however as the comparator itself is not templated anymore.

I compiled both versions with GCC 8.1, the clang 6.0 build clears the parts where the error occurs but fails later due to the `SUMOSAXAttributes` problem @sxleixer mentioned.

**Comment by namdre** [comment]
@mightyCelu I would integrate your second version if you issue a  pull request. I think it is nicer because the amount of code when using the comparator is reduced. If you put it outside the class but into the same file that would be fine too.

According to your finding, it should also be sufficient to include MSLane.h in MSEdgeControl.h to fix this issue. While that would be less invasive, I think your solution is cleaner.

**Comment by mightyCelu** [comment]
I opened a PR (#4130). It compiles for me, but I suppose it'd be good if others could test it before merging.
