### ISSUE TITLE
AttributeError: 'Connection' object has no attribute '_socket'

### ISSUE THREAD

**Issue by MartijnHarmenzon** [eclipse/sumo#4645]
I am trying to run a SUMO (v1.0.1, Windows 10) simulation which was started from Python. SUMO-gui opens fine, and the simulation is also started without any problems. After about 69 simulation steps, the simulation stops with the error: "AttributeError: 'Connection' object has no attribute '_socket'". 

Do you have any suggestions on how to solve this? Or how to debug this error?

The code can be downloaded from GitHub:
https://github.com/MartijnHarmenzon/openTLC.git

To start SUMO from Python, the file 'k0001sumo.py' needs to be run.

**Comment by behrisch** [comment]
I see sumo aborting but not your error message, can you send the full stack trace?

**Comment by MartijnHarmenzon** [comment]
Thank you for your quick response. Where can I find the full stack trace?

**Comment by behrisch** [comment]
It is most likely not a fault with your script but with the E3 detectors. I could reproduce it with just replaying your traffic light sequence. The real error seems to be the first one where sumo closes the connection, the rest is just fallout.

**Comment by behrisch** [comment]
The immediate thing should be solved but work continues in #4680

**Comment by MartijnHarmenzon** [comment]
I downloaded the latest nighly snapshot. Unfortunately, I am still experiencing the exact same isue.

**Comment by behrisch** [comment]
Our windows build experienced some problems over the weekend. Please try again tomorrow.

**Comment by MartijnHarmenzon** [comment]
I can confirm that with the latest Windows build the simulation runs without any errors. Thank you.
