### ISSUE TITLE
netedit freezes when changing edge attribute

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6336]
- select all edges with type '0'
- inspect and change numLanes to 1
- ->freeze for 1-3 minutes

works instantly with version 1.3.1

network is in bugreports folder

**Comment by palvarezlopez** [comment]
@namdre can you check the solution?

**Comment by namdre** [comment]
It's still very slow. Please use the network in the bugreports folder to see for yourself.

**Comment by namdre** [comment]
netconvert is also slow on this network. I'll check it.

**Comment by namdre** [comment]
There is quite a bit of slowdown when computing the junction rules.
I'm downgrading the severity because junctions with a total of 280 incoming lanes aren't too common.

**Comment by palvarezlopez** [comment]
@namdre can you check if this problem persist?

**Comment by palvarezlopez** [comment]
Fixed in #6848

**Comment by namdre** [comment]
it still freezes but this is due to netconvert, not netedit.
