### ISSUE TITLE
support vTypeDistribution

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9435]
in the first step we don't even need to support them in the UI.
It would already help if input files with vTypeDistributions can be loaded and written without data loss.

**Comment by palvarezlopez** [comment]
Fixed

**Comment by namdre** [comment]
@palvarezlopez  There is still an error when trying to load a vehicle that has it's vType set to a vTypeDistribution id.

**Comment by palvarezlopez** [comment]
Continue in #9435
